# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :certificates do
    match(type: "development", app_identifier: ["in.wealthy.ios.wealthy.advisor.development"])
    match(type: "appstore")
  end
  lane :beta do
    increment_build_number
    match(type: "appstore")
    gym(scheme: "wlv1Production")
    #testflight
  end
end
